In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\hp\OneDrive\Desktop\dav\test.csv")
print(df)

     PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James
1            893       3              Wilkes, Mrs. James (Ellen Needs)
2            894       2                     Myles, Mr. Thomas Francis
3            895       3                              Wirz, Mr. Albert
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)
..           ...     ...                                           ...
413         1305       3                            Spector, Mr. Woolf
414         1306       1                  Oliva y Ocana, Dona. Fermina
415         1307       3                  Saether, Mr. Simon Sivertsen
416         1308       3                           Ware, Mr. Frederick
417         1309       3                      Peter, Master. Michael J

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked
0      male  34.5      0      0              330911    7.8292   NaN        Q
1    female  47.0      1      0              363272    7.0000   NaN        S
2      male  62.0      0      0              240276    9.6875   NaN        Q
3      male  27.0      0      0              315154    8.6625   NaN        S
4    female  22.0      1      1             3101298   12.2875   NaN        S
..      ...   ...    ...    ...                 ...       ...   ...      ...
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S
414  female  39.0      0      0            PC 17758  108.9000  C105        C
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S
416    male   NaN      0      0              359309    8.0500   NaN        S
417    male   NaN      1      1                2668   22.3583   NaN        C

[418 rows x 11 columns]

In [3]:
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [6]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    str
 3   Sex          418 non-null    str
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    str
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     str
 10  Embarked     418 non-null    str
dtypes: float64(2), int64(4), str(5)
memory usage: 36.1 KB
None

In [9]:
print(df.columns)

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [10]:
print(df.describe)

<bound method NDFrame.describe of      PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James
1            893       3              Wilkes, Mrs. James (Ellen Needs)
2            894       2                     Myles, Mr. Thomas Francis
3            895       3                              Wirz, Mr. Albert
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)
..           ...     ...                                           ...
413         1305       3                            Spector, Mr. Woolf
414         1306       1                  Oliva y Ocana, Dona. Fermina
415         1307       3                  Saether, Mr. Simon Sivertsen
416         1308       3                           Ware, Mr. Frederick
417         1309       3                      Peter, Master. Michael J

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked
0      male  34.5      0      0              330911    7.8292   NaN        Q
1    female  47.0      1      0              363272    7.0000   NaN        S
2      male  62.0      0      0              240276    9.6875   NaN        Q
3      male  27.0      0      0              315154    8.6625   NaN        S
4    female  22.0      1      1             3101298   12.2875   NaN        S
..      ...   ...    ...    ...                 ...       ...   ...      ...
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S
414  female  39.0      0      0            PC 17758  108.9000  C105        C
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S
416    male   NaN      0      0              359309    8.0500   NaN        S
417    male   NaN      1      1                2668   22.3583   NaN        C

[418 rows x 11 columns]>

In [15]:
(df["Fare"].mean())

np.float64(35.627188489208635)

In [16]:
print(df["Fare"].median())

14.4542

In [17]:
print(df["Fare"].mode())

0    7.75
Name: Fare, dtype: float64

In [18]:
print(df["Fare"].var())

3125.657074319579

In [19]:
print(df["Fare"].std())

55.907576179973844

In [20]:
print(df["Fare"].min())

0.0

In [21]:
print(df["Fare"].max())

512.3292

In [22]:
print(df["Fare"].count())

417

In [23]:
print(df["Fare"].unique())

[  7.8292   7.       9.6875   8.6625  12.2875   9.225    7.6292  29.
   7.2292  24.15     7.8958  26.      82.2667  61.175   27.7208  12.35
   7.225    7.925   59.4      3.1708  31.6833  61.3792 262.375   14.5
  61.9792  30.5     21.6792  31.5     20.575   23.45    57.75     8.05
   9.5     56.4958  13.4167  26.55     7.85    13.      52.5542  29.7
   7.75    76.2917  15.9     60.      15.0333  23.     263.      15.5792
  29.125    7.65    16.1     13.5      7.725   21.       7.8792  42.4
  28.5375 211.5     25.7     15.2458 221.7792  10.7083  14.4542  13.9
   7.775   52.       7.7958  78.85     7.8542  55.4417   8.5167  22.525
   7.8208   8.7125  15.0458   7.7792  31.6792   7.2833   6.4375  16.7
  75.2417  15.75     7.25    23.25    28.5     25.4667  46.9    151.55
  18.      51.8625  83.1583      nan  12.1833  31.3875   7.55    13.775
   7.7333  22.025   50.4958  34.375    8.9625  39.      36.75    53.1
 247.5208  16.      69.55    32.5    134.5     10.5      8.1125  15.5
  14.4    227.525   25.7417   7.05    73.5     42.5    164.8667  13.8583
  27.4458  15.1     65.       6.4958  71.2833  75.25   106.425   30.
   7.8875  27.75   136.7792   9.325   17.4     12.7375   0.      20.2125
  39.6      6.95    81.8583  41.5792  45.5      9.35    93.5     14.1083
   7.575  135.6333 146.5208 211.3375  79.2     15.7417   7.5792 512.3292
  63.3583  51.4792  15.55    37.0042  14.4583  39.6875  11.5     50.
  12.875   21.075   39.4     20.25    47.1     13.8625   7.7208  90.
 108.9     22.3583]

In [24]:
print(df["Fare"].nunique())

169

In [25]:
print(df["Fare"].value_counts())

Fare
7.7500      21
26.0000     19
8.0500      17
13.0000     17
7.8958      11
            ..
13.8625      1
7.7208       1
90.0000      1
108.9000     1
22.3583      1
Name: count, Length: 169, dtype: int64

In [26]:
print(df.isnull())

     PassengerId  Pclass   Name    Sex    Age  SibSp  Parch  Ticket   Fare  \
0          False   False  False  False  False  False  False   False  False
1          False   False  False  False  False  False  False   False  False
2          False   False  False  False  False  False  False   False  False
3          False   False  False  False  False  False  False   False  False
4          False   False  False  False  False  False  False   False  False
..           ...     ...    ...    ...    ...    ...    ...     ...    ...
413        False   False  False  False   True  False  False   False  False
414        False   False  False  False  False  False  False   False  False
415        False   False  False  False  False  False  False   False  False
416        False   False  False  False   True  False  False   False  False
417        False   False  False  False   True  False  False   False  False

     Cabin  Embarked
0     True     False
1     True     False
2     True     False
3     True     False
4     True     False
..     ...       ...
413   True     False
414  False     False
415   True     False
416   True     False
417   True     False

[418 rows x 11 columns]

In [27]:
print(df.isnull().sum())

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [28]:
print(df.isnull().mean()*100)

PassengerId     0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            20.574163
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.239234
Cabin          78.229665
Embarked        0.000000
dtype: float64

In [29]:
print(df.dropna())

     PassengerId  Pclass                                               Name  \
12           904       1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)
14           906       1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...
24           916       1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)
26           918       1                       Ostby, Miss. Helene Ragnhild
28           920       1                            Brady, Mr. John Bertram
..           ...     ...                                                ...
404         1296       1                       Frauenthal, Mr. Isaac Gerald
405         1297       2       Nourney, Mr. Alfred (Baron von Drachstedt")"
407         1299       1                         Widener, Mr. George Dunton
411         1303       1    Minahan, Mrs. William Edward (Lillian E Thorpe)
414         1306       1                       Oliva y Ocana, Dona. Fermina

        Sex   Age  SibSp  Parch         Ticket      Fare            Cabin  \
12   female  23.0      1      0          21228   82.2667              B45
14   female  47.0      1      0    W.E.P. 5734   61.1750              E31
24   female  48.0      1      3       PC 17608  262.3750  B57 B59 B63 B66
26   female  22.0      0      1         113509   61.9792              B36
28     male  41.0      0      0         113054   30.5000              A21
..      ...   ...    ...    ...            ...       ...              ...
404    male  43.0      1      0          17765   27.7208              D40
405    male  20.0      0      0  SC/PARIS 2166   13.8625              D38
407    male  50.0      1      1         113503  211.5000              C80
411  female  37.0      1      0          19928   90.0000              C78
414  female  39.0      0      0       PC 17758  108.9000             C105

    Embarked
12         S
14         S
24         C
26         C
28         S
..       ...
404        C
405        C
407        C
411        Q
414        C

[87 rows x 11 columns]

In [30]:
print(df.fillna(0))

     PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James
1            893       3              Wilkes, Mrs. James (Ellen Needs)
2            894       2                     Myles, Mr. Thomas Francis
3            895       3                              Wirz, Mr. Albert
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)
..           ...     ...                                           ...
413         1305       3                            Spector, Mr. Woolf
414         1306       1                  Oliva y Ocana, Dona. Fermina
415         1307       3                  Saether, Mr. Simon Sivertsen
416         1308       3                           Ware, Mr. Frederick
417         1309       3                      Peter, Master. Michael J

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked
0      male  34.5      0      0              330911    7.8292     0        Q
1    female  47.0      1      0              363272    7.0000     0        S
2      male  62.0      0      0              240276    9.6875     0        Q
3      male  27.0      0      0              315154    8.6625     0        S
4    female  22.0      1      1             3101298   12.2875     0        S
..      ...   ...    ...    ...                 ...       ...   ...      ...
413    male   0.0      0      0           A.5. 3236    8.0500     0        S
414  female  39.0      0      0            PC 17758  108.9000  C105        C
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500     0        S
416    male   0.0      0      0              359309    8.0500     0        S
417    male   0.0      1      1                2668   22.3583     0        C

[418 rows x 11 columns]

In [31]:
print(df.duplicated())

0      False
1      False
2      False
3      False
4      False
       ...
413    False
414    False
415    False
416    False
417    False
Length: 418, dtype: bool

In [32]:
print(df.duplicated().sum())

0

In [33]:
print(df.drop_duplicates())

     PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James
1            893       3              Wilkes, Mrs. James (Ellen Needs)
2            894       2                     Myles, Mr. Thomas Francis
3            895       3                              Wirz, Mr. Albert
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)
..           ...     ...                                           ...
413         1305       3                            Spector, Mr. Woolf
414         1306       1                  Oliva y Ocana, Dona. Fermina
415         1307       3                  Saether, Mr. Simon Sivertsen
416         1308       3                           Ware, Mr. Frederick
417         1309       3                      Peter, Master. Michael J

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked
0      male  34.5      0      0              330911    7.8292   NaN        Q
1    female  47.0      1      0              363272    7.0000   NaN        S
2      male  62.0      0      0              240276    9.6875   NaN        Q
3      male  27.0      0      0              315154    8.6625   NaN        S
4    female  22.0      1      1             3101298   12.2875   NaN        S
..      ...   ...    ...    ...                 ...       ...   ...      ...
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S
414  female  39.0      0      0            PC 17758  108.9000  C105        C
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S
416    male   NaN      0      0              359309    8.0500   NaN        S
417    male   NaN      1      1                2668   22.3583   NaN        C

[418 rows x 11 columns]

In [34]:
print(df[["Fare","Age"]])

         Fare   Age
0      7.8292  34.5
1      7.0000  47.0
2      9.6875  62.0
3      8.6625  27.0
4     12.2875  22.0
..        ...   ...
413    8.0500   NaN
414  108.9000  39.0
415    7.2500  38.5
416    8.0500   NaN
417   22.3583   NaN

[418 rows x 2 columns]

In [35]:
df.sort_values("Age")

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
354,1246,3,"Dean, Miss. Elizabeth Gladys Millvina""""",female,0.17,1,2,C.A. 2315,20.5750,NaN,S
201,1093,3,"Danbom, Master. Gilbert Sigvard Emanuel",male,0.33,0,2,347080,14.4000,NaN,S
281,1173,3,"Peacock, Master. Alfred Edward",male,0.75,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S
307,1199,3,"Aks, Master. Philip Frank",male,0.83,0,1,392091,9.3500,NaN,S
250,1142,2,"West, Miss. Barbara J",female,0.92,1,2,C.A. 34651,27.7500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
408,1300,3,"Riordan, Miss. Johanna Hannah""""",female,NaN,0,0,334915,7.7208,NaN,Q
410,1302,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [36]:
df.rename(columns={"Age":"c age"})

,PassengerId,Pclass,Name,Sex,c age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [37]:
df.groupby("Age")

In [ ]:
df.shape